### ISSUE TITLE
7.124.424 - Line 10811 has error='key not found in database'

### ISSUE THREAD

**Issue by smeee-again** [kw123/pibeacon#2]
Upon upgrading to v7.124.424, I'm getting the following error.

`Aug 24, 2020 at 1:27:36 PM
   Enabling plugin "piBeacon 7.124.424"
   Starting plugin "piBeacon 7.124.424" (pid 14794)
   piBeacon                        initializing	 ... 
   piBeacon                        path To files:          =================
   piBeacon                        indigo                  /Library/Application Support/Perceptive Automation/
   piBeacon                        installFolder           /Library/Application Support/Perceptive Automation/Indigo 7.4/
   piBeacon                        plugin.py               /Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/piBeacon.indigoPlugin/Contents/Server Plugin/
   piBeacon                        Plugin params           /Library/Application Support/Perceptive Automation/Indigo 7.4/Preferences/Plugins/com.karlwachs.piBeacon/
   piBeacon Warning                !!!!INFO ONLY!!!!  logger  enabled for   WARNING       !!!!INFO ONLY!!!!
   piBeacon Error                  !!!!INFO ONLY!!!!  logger  enabled for   ERROR         !!!!INFO ONLY!!!!
   piBeacon Critical Error         !!!!INFO ONLY!!!!  logger  enabled for   CRITICAL      !!!!INFO ONLY!!!!
   piBeacon                        check                   /Library/Application Support/Perceptive Automation/Indigo 7.4/Logs/com.karlwachs.piBeacon/plugin.log  <<<<    for detailed logging
   piBeacon                        Plugin short Name       piBeacon
   piBeacon                        my PID                  14794
   piBeacon                        set params for indigo V 7.4
   Started plugin "piBeacon 7.124.424"
   piBeacon                        myLogSet setting parameters -- logFileActive= indigo; logFile= /Library/Application Support/Perceptive Automation/Indigo 7.4/Logs/com.karlwachs.piBeacon/plugin.log;  debug plugin:[]   RPI#:-1
   piBeacon                        testing if variable enableTimeTracking_piBeacon is == on/off/print-option to enable/end/print time tracking of all functions and methods (option:'',calls,cumtime,pcalls,time)
   piBeacon                         --V 7.124.424   initializing  -- 
   piBeacon                         ..  initialized

Aug 24, 2020 at 1:28:16 PM
   piBeacon Error                  Line 10811 has error='key not found in database'
   piBeacon Error                  Line 10811 has error='key not found in database'
   piBeacon Error                  Line 10811 has error='key not found in database'
   piBeacon Error                  Line 10811 has error='key not found in database'
   piBeacon Error                  Line 10811 has error='key not found in database'
   piBeacon Error                  Line 10811 has error='key not found in database'
   piBeacon Error                  Line 10811 has error='key not found in database'
   piBeacon Error                  Line 10811 has error='key not found in database'
   piBeacon Error                  Line 10811 has error='key not found in database'
   piBeacon Error                  Line 10811 has error='key not found in database'
   piBeacon Error                  Line 10811 has error='key not found in database'
   piBeacon Error                  Line 10811 has error='key not found in database'
`

**Comment by kw123** [comment]
will fix today .. 

Karl

**Comment by kw123** [comment]
try this one:
https://github.com/kw123/pibeacon/releases/tag/v7.124.428

**Comment by smeee-again** [comment]
New error:

`Aug 24, 2020 at 2:08:50 PM
   Indigo Cocoa client connected
   Upgrading plugin piBeacon to newer version 7.124.428 (previous version moved to trash)
   Loading plugin "piBeacon 7.124.428"
   Starting plugin "piBeacon 7.124.428" (pid 15719)
   piBeacon                        initializing	 ... 
   piBeacon                        path To files:          =================
   piBeacon                        indigo                  /Library/Application Support/Perceptive Automation/
   piBeacon                        installFolder           /Library/Application Support/Perceptive Automation/Indigo 7.4/
   piBeacon                        plugin.py               /Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/piBeacon.indigoPlugin/Contents/Server Plugin/
   piBeacon                        Plugin params           /Library/Application Support/Perceptive Automation/Indigo 7.4/Preferences/Plugins/com.karlwachs.piBeacon/
   piBeacon Warning                !!!!INFO ONLY!!!!  logger  enabled for   WARNING       !!!!INFO ONLY!!!!
   piBeacon Error                  !!!!INFO ONLY!!!!  logger  enabled for   ERROR         !!!!INFO ONLY!!!!
   piBeacon Critical Error         !!!!INFO ONLY!!!!  logger  enabled for   CRITICAL      !!!!INFO ONLY!!!!
   piBeacon                        check                   /Library/Application Support/Perceptive Automation/Indigo 7.4/Logs/com.karlwachs.piBeacon/plugin.log  <<<<    for detailed logging
   piBeacon                        Plugin short Name       piBeacon
   piBeacon                        my PID                  15719
   piBeacon                        set params for indigo V 7.4
   Started plugin "piBeacon 7.124.428"
   piBeacon                        myLogSet setting parameters -- logFileActive= indigo; logFile= /Library/Application Support/Perceptive Automation/Indigo 7.4/Logs/com.karlwachs.piBeacon/plugin.log;  debug plugin:[]   RPI#:-1
   piBeacon                        testing if variable enableTimeTracking_piBeacon is == on/off/print-option to enable/end/print time tracking of all functions and methods (option:'',calls,cumtime,pcalls,time)
   piBeacon                         --V 7.124.428   initializing  -- 
   piBeacon                         ..  initialized

Aug 24, 2020 at 2:09:21 PM
   piBeacon Error                  Line 10827 has error='key not found in database'
   piBeacon Error                  Line 10827 has error='key not found in database'
   piBeacon Error                  Line 10827 has error='key not found in database'
   piBeacon Error                  Line 10827 has error='key not found in database'
   piBeacon Error                  Line 10827 has error='key not found in database'
   piBeacon Error                  Line 10827 has error='key not found in database'
   piBeacon Error                  Line 10827 has error='key not found in database'
   piBeacon Error                  Line 10827 has error='key not found in database'
   piBeacon Error                  Line 10827 has error='key not found in database'
   piBeacon Error                  Line 10827 has error='key not found in database'
   piBeacon Error                  Line 10827 has error='key not found in database'
   piBeacon Error                  Line 10827 has error='key not found in database'
   piBeacon Error                  Line 10827 has error='key not found in database'
   piBeacon Error                  Line 10827 has error='key not found in database'
`

**Comment by kw123** [comment]
I edited the wrong plugin file… will correct

**Comment by kw123** [comment]
published formal release on indigo store (and GitHub) if you like to down load.

**Comment by smeee-again** [comment]
This issue appears to be resolved.  I installed the updated plugin and no errors for about 50 minutes; normally after a few minutes the errors would start.

`Aug 24, 2020 at 8:01:56 PM
   piBeacon Error                  Line 10827 has error='key not found in database'
   piBeacon Error                  Line 10827 has error='key not found in database'
   Stopping plugin piBeacon (pid 19664)
   piBeacon                        stop requested from indigo 
   piBeacon                         .. quitNow:  empty
   Stopped plugin piBeacon
   Upgrading plugin piBeacon to newer version 7.124.430 (previous version moved to trash)
   Loading plugin "piBeacon 7.124.430"
   Starting plugin "piBeacon 7.124.430" (pid 19800)
   piBeacon                        initializing	 ... 
   piBeacon                        path To files:          =================
   piBeacon                        indigo                  /Library/Application Support/Perceptive Automation/
   piBeacon                        installFolder           /Library/Application Support/Perceptive Automation/Indigo 7.4/
   piBeacon                        plugin.py               /Library/Application Support/Perceptive Automation/Indigo 7.4/Plugins/piBeacon.indigoPlugin/Contents/Server Plugin/
   piBeacon                        Plugin params           /Library/Application Support/Perceptive Automation/Indigo 7.4/Preferences/Plugins/com.karlwachs.piBeacon/
   piBeacon Warning                !!!!INFO ONLY!!!!  logger  enabled for   WARNING       !!!!INFO ONLY!!!!
   piBeacon Error                  !!!!INFO ONLY!!!!  logger  enabled for   ERROR         !!!!INFO ONLY!!!!
   piBeacon Critical Error         !!!!INFO ONLY!!!!  logger  enabled for   CRITICAL      !!!!INFO ONLY!!!!
   piBeacon                        check                   /Library/Application Support/Perceptive Automation/Indigo 7.4/Logs/com.karlwachs.piBeacon/plugin.log  <<<<    for detailed logging
   piBeacon                        Plugin short Name       piBeacon
   piBeacon                        my PID                  19800
   piBeacon                        set params for indigo V 7.4
   Started plugin "piBeacon 7.124.430"
   piBeacon                        myLogSet setting parameters -- logFileActive= indigo; logFile= /Library/Application Support/Perceptive Automation/Indigo 7.4/Logs/com.karlwachs.piBeacon/plugin.log;  debug plugin:[]   RPI#:-1
   piBeacon                        testing if variable enableTimeTracking_piBeacon is == on/off/print-option to enable/end/print time tracking of all functions and methods (option:'',calls,cumtime,pcalls,time)
   piBeacon                         --V 7.124.430   initializing  -- 
   piBeacon                         ..  initialized
Aug 24, 2020 at 8:48:51 PM
`

**Comment by kw123** [comment]
Did you use the latest v also published on the Indigo store?

Karl

**Comment by smeee-again** [comment]
I used the latest in the Indigo Domo plugin store; v7.124.430.
